# Site
title:              Dan Carmody
bio:                'Fellow at Insight Data Science'
description:        ""
reading_time:       true
words_per_minute:   200
logo:               'assets/img/moon_man.jpeg'
background:         'assets/img/whitney.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                http://www.danielcarmody.net
url:		    http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
kramdown:
  syntax_highlighter: pygments
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   true
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   dan

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            carmodydr
#facebook:           username
github:             carmodydr
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           dan-carmody
#xing:              username
instagram:          dancarmody
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
flickr:             carmodydr
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-coffeescript

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
